# - Find tulip
# Find the Tulip library.
#
#  TULIP_FOUND           True if tulip got found
#  TULIP_INCLUDE_DIRS    Location of tulip headers
#  TULIP_LIBRARIES       List of libraries to use tulip

# Look for the header file.
FIND_PATH(TULIP_INCLUDE_DIR NAMES Graph.h PATH_SUFFIXES tulip)

# Look for the library.
FIND_LIBRARY(TULIP_LIBRARY NAMES tulip)
FIND_LIBRARY(TULIP_OGL_LIBRARY NAMES tulip-ogl)
FIND_LIBRARY(TULIP_QT_LIBRARY NAMES tulip-qt4)

# Handle the QUIETLY and REQUIRED arguments and set TULIP_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TULIP DEFAULT_MSG TULIP_LIBRARY TULIP_OGL_LIBRARY TULIP_QT_LIBRARY TULIP_INCLUDE_DIR)

IF(TULIP_FOUND)
    SET(TULIP_LIBRARIES ${TULIP_LIBRARY} ${TULIP_OGL_LIBRARY} ${TULIP_QT_LIBRARY})
ELSE(TULIP_FOUND)
    SET(TULIP_LIBRARIES)
ENDIF(TULIP_FOUND)
